In [1]:
import numpy as np
import pandas as pd

import datetime
from datetime import datetime, date

pd.set_option('display.notebook_repr_html', False)
pd.set_option('display.max_columns', 8)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 80)

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
sp500 = pd.read_csv('../data/sp500.csv',
                   index_col = 'Symbol',
                   usecols = [0,2,3,7])

In [4]:
omh = pd.read_csv('../data/omh.csv')

# Performing arithmetic on a DF or Series

- DataFrame과 Series의 산술 연산: .add() / .sub() / .mul() / .div()

In [6]:
np.random.seed(123456)
df = pd.DataFrame(np.random.randn(5,4),
                 columns = ['A','B','C','D'])
df

          A         B         C         D
0  0.469112 -0.282863 -1.509059 -1.135632
1  1.212112 -0.173215  0.119209 -1.044236
2 -0.861849 -2.104569 -0.494929  1.071804
3  0.721555 -0.706771 -1.039575  0.271860
4 -0.424972  0.567020  0.276232 -1.087401

In [7]:
# mulstiply every elements by 2
df * 2

          A         B         C         D
0  0.938225 -0.565727 -3.018117 -2.271265
1  2.424224 -0.346429  0.238417 -2.088472
2 -1.723698 -4.209138 -0.989859  2.143608
3  1.443110 -1.413542 -2.079150  0.543720
4 -0.849945  1.134041  0.552464 -2.174801

In [9]:
# get first row
s = df.iloc[0]

# subtract first row from every row of the DF
s

A    0.469112
B   -0.282863
C   -1.509059
D   -1.135632
Name: 0, dtype: float64

In [11]:
s = df.iloc[0]

# subtract firwt row from every row of the DF
diff = df - s
diff

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1  0.743000  0.109649  1.628267  0.091396
2 -1.330961 -1.821706  1.014129  2.207436
3  0.252443 -0.423908  0.469484  1.407492
4 -0.894085  0.849884  1.785291  0.048232

In [12]:
# subtract DF from Series
diff2 = s -df
diff2

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1 -0.743000 -0.109649 -1.628267 -0.091396
2  1.330961  1.821706 -1.014129 -2.207436
3 -0.252443  0.423908 -0.469484 -1.407492
4  0.894085 -0.849884 -1.785291 -0.048232

In [13]:
# B, C
s2 = s[1:3]
s2

B   -0.282863
C   -1.509059
Name: 0, dtype: float64

In [14]:
df

          A         B         C         D
0  0.469112 -0.282863 -1.509059 -1.135632
1  1.212112 -0.173215  0.119209 -1.044236
2 -0.861849 -2.104569 -0.494929  1.071804
3  0.721555 -0.706771 -1.039575  0.271860
4 -0.424972  0.567020  0.276232 -1.087401

In [16]:
# add E
s2['E'] = 0

df + s2 # 로우 우선 브로드케스팅 각 컬럼의 서로 다른 값을 로우 단위에 적용

    A         B         C   D   E
0 NaN -0.565727 -3.018117 NaN NaN
1 NaN -0.456078 -1.389850 NaN NaN
2 NaN -2.387433 -2.003988 NaN NaN
3 NaN -0.989634 -2.548633 NaN NaN
4 NaN  0.284157 -1.232826 NaN NaN

In [17]:
# get rows 1 through three, and only B, C columns
subframe = df[1:4][['B','C']]

# we have extracted a little square in the middle of df
subframe

          B         C
1 -0.173215  0.119209
2 -2.104569 -0.494929
3 -0.706771 -1.039575

In [18]:
df - subframe

    A    B    C   D
0 NaN  NaN  NaN NaN
1 NaN  0.0  0.0 NaN
2 NaN  0.0  0.0 NaN
3 NaN  0.0  0.0 NaN
4 NaN  NaN  NaN NaN

In [19]:
# get the A column
a_col1 = df['A']
df.sub(a_col1, axis=0) # a_col1 - df 값 A열의 값을 B,C,D에 빼기 수식 적용

     A         B         C         D
0  0.0 -0.751976 -1.978171 -1.604745
1  0.0 -1.385327 -1.092903 -2.256348
2  0.0 -1.242720  0.366920  1.933653
3  0.0 -1.428326 -1.761130 -0.449695
4  0.0  0.991993  0.701204 -0.662428

# Counts of values

In [21]:
s = pd.Series(['a','a','b','c', np.NaN])

# number of occurences of each unique value
s.count() # nan이 아닌 아이템의 개수

4

# Unique and number of unique values

In [23]:
# return a list of unique items
s.unique() # 고유값 목록

array(['a', 'b', 'c', nan], dtype=object)

In [24]:
s.nunique() # nan 제외한 고유값 개수

3

In [25]:
s.nunique(dropna=False) # nan을 포함한 개수

4

In [26]:
# get summary stats on non-numeric data
s.value_counts(dropna=False) # 고유값 각각의 개수 . value_counts() 과정을 히스토그래밍

a      2
b      1
c      1
NaN    1
dtype: int64

In [27]:
omh[:5]

         Date   MSFT    AAPL
0  2014-12-01  48.62  115.07
1  2014-12-02  48.46  114.63
2  2014-12-03  48.08  115.93
3  2014-12-04  48.84  115.49
4  2014-12-05  48.42  115.00

In [28]:
# location of min price for both stocks
omh[['MSFT', 'AAPL']].min() # 최소값: .min()

MSFT     45.16
AAPL    106.75
dtype: float64

In [29]:
# and location of the max
omh[['MSFT','AAPL']].max() # 최대값: .max()

MSFT     48.84
AAPL    115.93
dtype: float64

In [31]:
# location of min price for both stocks
omh[['MSFT','AAPL']].idxmin() # 간접적으로 관련된 값을 반환, 최소값이 있는 포지션: .idxmin()

MSFT    11
AAPL    11
dtype: int64

In [33]:
# and location of the max
omh[['MSFT','AAPL']].idxmax()# 간접적으로 관련된 값을 반환, 최대값이 있는 포지션: .idxmin()

MSFT    3
AAPL    2
dtype: int64

# Smallest and Largest Values (n개 최솟값과 n개 최댓값 찾기)

In [34]:
# get the 4 smallest values
omh.nsmallest(4, ['MSFT'])['MSFT'] # MSFT 칼럼에서 가장 작은 값 4개 조회

11    45.16
12    45.74
21    46.45
10    46.67
Name: MSFT, dtype: float64

In [36]:
omh.nsmallest(4, ['MSFT'])['AAPL']

11    106.75
12    109.41
21    110.38
10    108.23
Name: AAPL, dtype: float64

In [35]:
# get the 4 largest values
omh.nlargest(4, ['MSFT'])['MSFT'] # MSFT 칼럼에서 가장 큰 값 4개 조회

3     48.84
0     48.62
1     48.46
16    48.45
Name: MSFT, dtype: float64

# Accumulations(누적 값 계산에 연속으로 적용한 통계 방법, 누적 곱, 누적 합)

In [38]:
# calculate a cumulative product
pd.Series([1,2,3,4]).cumprod() # 누적 곱: .comprod()

0     1
1     2
2     6
3    24
dtype: int64

In [39]:
# calculate a cumulative sum
pd.Series([1,2,3,4]).cumsum() #누적 합계: .comsum()

0     1
1     3
2     6
3    10
dtype: int64

In [40]:
omh.AAPL.cumsum()

0      115.07
1      229.70
2      345.63
3      461.12
4      576.12
       ...   
17    2022.25
18    2136.24
19    2250.15
20    2362.67
21    2473.05
Name: AAPL, Length: 22, dtype: float64

In [42]:
omh[['MSFT','AAPL']].cumsum()

       MSFT     AAPL
0     48.62   115.07
1     97.08   229.70
2    145.16   345.63
3    194.00   461.12
4    242.42   576.12
..      ...      ...
17   856.05  2022.25
18   903.93  2136.24
19   951.38  2250.15
20   998.40  2362.67
21  1044.85  2473.05

[22 rows x 2 columns]

# Summary descriptive statistics(객체의 통계 처리)
- 약식 기술 통계, 중심 경향성 측정: 평균, 중위수, 최빈수 분산과 표준 편차

In [43]:
# get summary statistics for the stock data
omh.describe() # 데이터의 개수, 평균, 표준 편차, 최솟값, 25, 50, 75 백북위, 최대값

            MSFT        AAPL
count  22.000000   22.000000
mean   47.493182  112.411364
std     0.933077    2.388772
min    45.160000  106.750000
25%    46.967500  111.660000
50%    47.625000  112.530000
75%    48.125000  114.087500
max    48.840000  115.930000

In [44]:
# just the stats for MSFT
omh.MSFT.describe()

count    22.000000
mean     47.493182
std       0.933077
min      45.160000
25%      46.967500
50%      47.625000
75%      48.125000
max      48.840000
Name: MSFT, dtype: float64

In [45]:
# only the mean for MSFT
omh.MSFT.describe()['mean']

47.49318181818182

In [46]:
omh.MSFT.describe()['max']

48.84

In [48]:
# get summary stats on non-numeric data
s = pd.Series(['a','a','b','c', np.NaN]) # 데이터의 통계, 아이템의 총 개수(count), 고윳값의 개수(unique), 최다 발생 값(top), 빈도수(freq)
s.describe()

count     4
unique    3
top       a
freq      2
dtype: object

# Mean 중심 경향성 측정: 평균, 중위수, 최빈수

In [49]:
# the mean of all the columns in omh
omh.mean() #중심 경향성 측정

MSFT     47.493182
AAPL    112.411364
dtype: float64

In [51]:
# calc the mean of the values in each row
omh.mean(axis=1)[:5] #mean() 메소드는 기본으로 axis=0

0    81.845
1    81.545
2    82.005
3    82.165
4    81.710
dtype: float64

In [52]:
omh.mean(axis=0)

MSFT     47.493182
AAPL    112.411364
dtype: float64

# Median

In [53]:
# cals the median of the values in each column
omh.median() # 중위수(중앙값, 중간값) 중앙에 위치한 값

MSFT     47.625
AAPL    112.530
dtype: float64

# Mode(최빈수 Series 안에 가장 많이 존재하는 값)

In [54]:
# find the mode of this Series
s = pd.Series([1,2,3,3,5]) # 빈도: 가장 많이 존재하는 값
s.mode()

0    3
dtype: int64

In [55]:
# there can be more than one mode
s = pd.Series([1,2,3,3,5,1])
s.mode()

0    1
1    3
dtype: int64

# Variance(분산은 모든 값이 평균으로부터 떨어져 있는 정도)

In [56]:
# calc the variance of the values in each column
omh.var() # 분산: 각 값과 평균과의 차이 측정, 제곱에 따라 음수의 누적 효과와 함꼐 결과로 반영

MSFT    0.870632
AAPL    5.706231
dtype: float64

# Standard Deviation

In [59]:
omh.std() # 표준편차: 자료의 산포도를 나타내는 수치, 분산의 양의 제곱근, 표준편차가 작을수록 평균값에 가까이에 데이터들이 분포 

MSFT    0.933077
AAPL    2.388772
dtype: float64

# Covariance: 공분산 - 두 개의 변수가 어떤 관계인지 설명

In [61]:
omh.MSFT.cov(omh.AAPL)
# 공분산: 두 개의 변수가 어떤 관계인지 설명
# 공분산은 두 변수가 각각의 평균에 대해서 얼마나 떨어져 있는지 기준을 정하기 애매함

1.9261240259740264

# Correlation

In [63]:
omh.MSFT.corr(omh.AAPL) # 상관관계 해당 분야의 사장 상황 등과 같이 두 주가에 동일한 영향을 주는 요소

0.8641560684381171

# Discretization and quatiling
- 이산화와 분위수: 이산화는 연속적인 데이터를 일련의 구간으로 분할하는 방법

In [64]:
np.random.seed(123456)
dist = np.random.normal(size = 10000)
dist

array([ 0.4691123 , -0.28286334, -1.5090585 , ...,  0.26296448,
       -0.83377412, -0.10418135])

In [65]:
(dist.mean(), dist.std())

(-0.002863324040906651, 1.008716203199891)

In [66]:
# cut into 5 equally sized bins
bins = pd.cut(dist, 5) # 동일한 크기의 구간 분할 5개로 구간 분할
bins

[(-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-2.077, -0.633], (0.81, 2.254], ..., (-2.077, -0.633], (-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-0.633, 0.81]]
Length: 10000
Categories (5, interval[float64]): [(-3.528, -2.077] < (-2.077, -0.633] < (-0.633, 0.81] < (0.81, 2.254] < (2.254, 3.698]]

In [67]:
bins.categories

IntervalIndex([(-3.528, -2.077], (-2.077, -0.633], (-0.633, 0.81], (0.81, 2.254], (2.254, 3.698]],
              closed='right',
              dtype='interval[float64]')

In [68]:
bins.codes

array([2, 2, 1, ..., 2, 1, 2], dtype=int8)

In [69]:
pd.cut(dist, 5, right=False).categories

IntervalIndex([[-3.521, -2.077), [-2.077, -0.633), [-0.633, 0.81), [0.81, 2.254), [2.254, 3.705)],
              closed='left',
              dtype='interval[float64]')

In [70]:
np.random.seed(123456)
ages = np.random.randint(6, 45, 50) # 50개 난수
ages

array([ 7, 33, 38, 29, 42, 14, 16, 16, 18, 17, 26, 28, 44, 40, 20, 12,  8,
       10, 36, 29, 26, 26, 11, 29, 42, 17, 41, 35, 22, 40, 24, 21, 38, 33,
       26, 23, 16, 34, 26, 20, 18, 42, 27, 13, 37, 37, 10,  7, 10, 23])

In [71]:
ranges = [6, 12, 18, 35, 50]
agebins = pd.cut(ages, ranges) # 9~12, 13~18
agebins.describe()

            counts  freqs
categories               
(6, 12]          8   0.16
(12, 18]         9   0.18
(18, 35]        21   0.42
(35, 50]        12   0.24

In [72]:
ranges = [6, 12, 18, 35, 50]
agebins = pd.cut(ages, ranges, right=False) # 9~12, 13~18
agebins.describe()

            counts  freqs
categories               
[6, 12)          7   0.14
[12, 18)         8   0.16
[18, 35)        22   0.44
[35, 50)        13   0.26

In [75]:
# add names for the bins
ranges = [6, 12, 18, 35, 50]
labels = ['Youth', 'Young Adult','Adult','Middle Aged']
agebins = pd.cut(ages, ranges, labels=labels)
agebins.describe()

             counts  freqs
categories                
Youth             8   0.16
Young Adult       9   0.18
Adult            21   0.42
Middle Aged      12   0.24

In [76]:
bins

[(-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-2.077, -0.633], (0.81, 2.254], ..., (-2.077, -0.633], (-0.633, 0.81], (-0.633, 0.81], (-2.077, -0.633], (-0.633, 0.81]]
Length: 10000
Categories (5, interval[float64]): [(-3.528, -2.077] < (-2.077, -0.633] < (-0.633, 0.81] < (0.81, 2.254] < (2.254, 3.698]]

In [77]:
qbin = pd.cut(dist, 5)
qbin
qbin.describe()

                  counts   freqs
categories                      
(-3.528, -2.077]     202  0.0202
(-2.077, -0.633]    2463  0.2463
(-0.633, 0.81]      5182  0.5182
(0.81, 2.254]       2033  0.2033
(2.254, 3.698]       120  0.0120

In [79]:
# cut into quantiles: 값이 5개씩 들어가는 구간 설정
qbin = pd.qcut(dist, 5)
qbin.describe()

                  counts  freqs
categories                     
(-3.522, -0.861]    2000    0.2
(-0.861, -0.241]    2000    0.2
(-0.241, 0.261]     2000    0.2
(0.261, 0.866]      2000    0.2
(0.866, 3.698]      2000    0.2

In [80]:
# make the quantiles at the +/- 3, 2 and 1 std deviations
quantiles = [0,
            0.001,
            0.021,
            0.5-0.341,
            0.5,
            0.5+0.341,
            1.0-0.021,
            1.0-0.001,
            1.0]
qbin = pd.qcut(dist, quantiles)

qbin.describe()

                    counts  freqs
categories                       
(-3.522, -3.131]        10  0.001
(-3.131, -2.056]       200  0.020
(-2.056, -1.033]      1380  0.138
(-1.033, -0.00363]    3410  0.341
(-0.00363, 1.011]     3410  0.341
(1.011, 2.043]        1380  0.138
(2.043, 3.062]         200  0.020
(3.062, 3.698]          10  0.001